### ISSUE TITLE
Bad path in Gemfile file

### ISSUE THREAD

**Issue by jasnow** [tgxworld/test-app#1]
Get this:

```
The path `/home/guoxiang/work/rails-dev-box/rails` does not exist.
```

when I try to run "rake" after "git clone"ing it.

**Comment by tgxworld** [comment]
@jasnow O you can change it to `github: rails/rails`. I was testing it against my local folder of Rails.

**Comment by jasnow** [comment]
Did that and add ".ruby-version" with "2.2.2" to use right version of ruby, I get this:

```
  1) PostsController#index 
     Failure/Error: it { assigns(:posts) }
     NoMethodError:
       assigns has been extracted to a gem. To continue using it,
               add `gem 'rails-controller-testing'` to your Gemfile.
     # /home/jasnow/.rvm/gems/ruby-2.2.2/bundler/gems/rails-0de359c5ef3b/actionpack/lib/action_dispatch/testing/test_process.rb:8:in `assigns'
     # ./spec/controllers/posts_controller_spec.rb:5:in `block (3 levels) in <top (required)>'
```

**Comment by tgxworld** [comment]
Could you try running `rake test`?

The `RSpec` failure is confirmed. From my brief look, that is because RSpec implements `assign` and calls `super` which directly calls the removed method.

**Comment by jasnow** [comment]
Confirmed - "rake test" did not get the message.

**Comment by jasnow** [comment]
Old issue, closing.
